name: Test VM Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Test on Test VM
        run: |
          echo "Running on:"
          hostname
          echo "Current user:"
          whoami
          echo "Current directory:"
          pwd
          echo "index.html content:"
          cat index.html
